### ISSUE TITLE
Playlist action forces shuffle to false

### ISSUE THREAD

**Issue by seigneurao** [sam-horne/streamdeck-mediamonkey5#4]
Hello !

Thanks for your great plugin.

I have a small issue.
When I launch a playlist from the Stream Deck, MediaMonkey shuffle setting is forced to false, regardless of its previous state.

Maybe caused by the following line
mediamonkey.js, L227 :
      '        player.shufflePlaylist = false;',

Existing global shuffle setting should be kept, as a default. Maybe a checkbox in the action settings on the Stream Deck, to indicate whether we wish to shuffle the playlist or not when we launch it ? As is the case in Mediamonkey itself.
See attached pic
![image](https://github.com/user-attachments/assets/c01e0e43-722e-41b7-b11b-b838e290caa9)

**Comment by sam-horne** [comment]
I think it makes sense to implement an option for actions that add to the now playing list to either force shuffle on/off or retain the current state.

**Comment by sam-horne** [comment]
Implemented in 0aa7201e0ae9f1d6c112fd064952344caec3b76f
